const iconSize = 70

const technologies = {
  go: { icon: "/icons/go.svg", title: "Go", iconSize },
  python: { icon: "/icons/python.svg", title: "Python", iconSize },
  php: { icon: "/icons/php.svg", title: "PHP", iconSize: 100 },
  html: { icon: "/icons/html5.svg", title: "HTML", iconSize },
  css: { icon: "/icons/css.svg", title: "CSS", iconSize },
  sass: { icon: "/icons/sass.svg", title: "SASS", iconSize },
  javascript: { icon: "/icons/javascript.svg", title: "Javascript", iconSize },
  typescript: { icon: "/icons/typescript.svg", title: "Typescript", iconSize },
  pwa: { icon: "/icons/pwa.svg", title: "PWA", iconSize },
  websocket: { icon: "/icons/websocket.svg", title: "Websocket", iconSize },
  next: { icon: "/icons/next.svg", title: "Next.js", iconSize },
  react: { icon: "/icons/react.svg", title: "React", iconSize },
  angular: { icon: "/icons/angular.svg", title: "Angular", iconSize },
  vue: { icon: "/icons/vue.svg", title: "Vue", iconSize },
  nodejs: { icon: "/icons/nodejs.svg", title: "Node.js", iconSize },
  wordpress: { icon: "/icons/wordpress.svg", title: "WordPress", iconSize },
  laravel: { icon: "/icons/laravel.svg", title: "Laravel", iconSize },
  django: { icon: "/icons/django.svg", title: "Django", iconSize },
  tailwindcss: { icon: "/icons/tailwindcss.svg", title: "Tailwind", iconSize },
  bootstrap: { icon: "/icons/bootstrap.svg", title: "Bootstrap", iconSize },
  shopify: { icon: "/icons/shopify.svg", title: "Shopify", iconSize },
  woocommerce: { icon: "/icons/woocommerce.svg", title: "WooCommerce", iconSize: 100 },
  stripe: { icon: "/icons/stripe.svg", title: "Stripe", iconSize },
  paypal: { icon: "/icons/paypal.svg", title: "PayPal", iconSize },
  mercado: { icon: "/icons/mercado-pago.svg", title: "Mercado Pago", iconSize },
  graphql: { icon: "/icons/graphql.svg", title: "GraphQL", iconSize },
  postgresql: { icon: "/icons/postgresql.svg", title: "PostgreSQL", iconSize },
  mongodb: { icon: "/icons/mongodb.svg", title: "MongoDB", iconSize: 40 },
  redis: { icon: "/icons/redis.svg", title: "REDIS", iconSize },
  valkey: { icon: "/icons/valkey.png", title: "Valkey", iconSize },
  prisma: { icon: "/icons/prisma.svg", title: "Prisma", iconSize },
  mysql: { icon: "/icons/mysql.svg", title: "MySQL", iconSize },
  sqlite: { icon: "/icons/sqlite.svg", title: "SQLite", iconSize },
  mariadb: { icon: "/icons/mariadb.svg", title: "MariaDB", iconSize },
  aws: { icon: "/icons/aws.svg", title: "AWS", iconSize },
  digitalocean: { icon: "/icons/digitalocean.svg", title: "Digitalocean", iconSize },
  cloudflare: { icon: "/icons/cloudflare.svg", title: "Cloudflare", iconSize },
  docker: { icon: "/icons/docker.svg", title: "Docker", iconSize },
  git: { icon: "/icons/git.svg", title: "Git", iconSize },
  bash: { icon: "/icons/bash.svg", title: "Bash", iconSize },
  linux: { icon: "/icons/linux.svg", title: "Linux", iconSize },
  apple: { icon: "/icons/apple.svg", title: "macOS/iOS", iconSize },
  windows: { icon: "/icons/windows.svg", title: "Windows", iconSize },
  android: { icon: "/icons/android.svg", title: "Android", iconSize },
  liquid: { icon: "/icons/liquid.png", title: "Liquid", iconSize },
  recaptcha: { icon: "/icons/recaptcha.svg", title: "reCAPTCHA", iconSize },
  hcaptcha: { icon: "/icons/hcaptcha.svg", title: "hCaptcha", iconSize },
  analytics: { icon: "/icons/analytics.svg", title: "Google Analytics", iconSize },
  tagmanager: { icon: "/icons/tagmanager.svg", title: "Google Tag Manager", iconSize },
  webcomponents: { icon: "/icons/webcomponents.svg", title: "Web Components", iconSize },
}

type TechnologyKey = keyof typeof technologies

export { technologies, type TechnologyKey }